name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Inject API Keys
        run: |
          sed -i 's/ca5c6d6fa3mshfcd2b0a0feac6b7p140e57jsn72684628152a/${{ secrets.RAPIDAPI_KEY }}/g' config.js

      - name: Deploy to GitHub Pages
        uses: Peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
